config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/recipes/drafts', to: 'recipes#drafts'
  resources :recipes, only: [:show, :new, :create, :edit, :update, :index] do
    patch :publish, on: :member
    patch :draft, on: :member
  end
  resources :recipe_types, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  enum status: { draft: 0, published: 2 }
  belongs_to :recipe_type
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all.count
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  def new
    @recipe_type = RecipeType.new
  end

  def create
    recipe_type_params = params.require(:recipe_type).permit(:name)
    @recipe_type = RecipeType.new(recipe_type_params)
    if @recipe_type.save
      flash['alert'] = 'Tipo de receita gravado com sucesso'
      return redirect_to new_recipe_type_path
    end
    flash.now['alert'] = 'Não foi possível salvar novo tipo de receita'
    render 'new'
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.published
  end
  
  def new
    @recipe = Recipe.new
  end

  def create
    recipe_params = params.require(:recipe).permit(:name,:recipe_type_id,:cuisine,:ingredients,:cook_method,:cook_time)
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      return redirect_to @recipe
    end
    flash.now['alert'] = 'Não foi possível salvar'
    render 'new'
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    recipe_params = params.require(:recipe).permit(:name,:recipe_type_id,:cuisine,:ingredients,:cook_method,:cook_time)
    if @recipe.update(recipe_params)
      return redirect_to @recipe
    end
    flash.now['alert'] = 'Não foi possível alterar'
    render 'edit'
  end

  def publish
    @recipe = Recipe.find(params[:id])
    @recipe.published!
    return redirect_to @recipe
  end

  def draft
    @recipe = Recipe.find(params[:id])
    @recipe.draft!
    return redirect_to @recipe
  end

  def drafts
    @recipes = Recipe.draft
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
  <br>
  <br>
  <h1>Olá, seja bem-vindo ao <i class="fas fa-cookie-bite"></i>CookBook</h1>
  <br><br>
  <h2>Você tem o total de <%= @recipes %> receitas cadastradas.</h2> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <style>
      /* Show it's not fixed to the top */
      body {
        min-height: 100vh;
        min-height: -webkit-fill-available;
      }

      html {
        height: -webkit-fill-available;
      }

      main {
        display: flex;
        flex-wrap: nowrap;
        height: 100vh;
        height: -webkit-fill-available;
        max-height: 100vh;
        overflow-x: auto;
        overflow-y: hidden;
      }
      .dropdown-toggle { outline: 0; }
    </style>
  </head>

  <body>
    <main>
      <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
          <i class="fas fa-cookie-bite"></i>
          <span class="fs-4" style="margin-left:0.2em;">CookBook</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="/" class="nav-link text-white" aria-current="page">
              <i class="fas fa-home"></i>
              Início
            </a>
          </li>
          <li>
            <a href="/recipe_types/new" class="nav-link text-white dropdown dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="far fa-book"></i>
              Receitas
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="/recipes/">Visualizar Receitas</a></li>
              <li><a class="dropdown-item" href="/recipes/new">Cadastrar Receitas</a></li>
              <li><a class="dropdown-item" href="/recipes/drafts">Rascunhos</a></li>
            </ul>
          </li>
          <li>
            <a href="/recipe_types/new" class="nav-link text-white dropdown dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="far fa-bookmark"></i>
              Tipos de Receitas
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="/recipe_types/new">Cadastrar</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width:62rem">
        <%= flash['alert'] %>
        <%= yield %>
      </div>
    </main>
    <footer></footer>
  </body>
</html>

app/views/recipe_types/new.html.erb
<h2><strong>Cadastro de Tipo de Receita</strong></h2>
<div style="width:20rem;">
  <%= form_with model: @recipe_type do |f| %>
    <div class="form-group">
      <b><%= f.label :name, 'Nome' %></b>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <br>
    <%= f.submit 'Gravar', class: "btn btn-success" %>
  <% end %>
</div>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe do |f| %>
  <div class="form-group">
    <b><%= f.label :name, 'Nome' %></b>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <b><%= f.label :recipe_type_id, 'Tipo da receita' %></b>
    <%= f.collection_select(:recipe_type_id, RecipeType.all, :id, :name, {}, { class: "form-control" }) %>
  </div>
  <div class="form-group">
    <b><%= f.label :cuisine, 'Culinária' %></b>
    <%= f.text_field :cuisine, class: "form-control" %>
  </div>
  <div class="form-group">
    <b><%= f.label :ingredients, 'Ingredientes' %></b>
    <%= f.text_area :ingredients, class: "form-control" %>
  </div>
  <div class="form-group">
    <b><%= f.label :cook_method, 'Método de preparo' %></b>
    <%= f.text_area :cook_method, class: "form-control" %>
  </div>
  <div class="form-group">
    <b><%= f.label :cook_time, 'Tempo de preparo' %></b>
    <%= f.number_field :cook_time, class: "form-control" %>
  </div>
  <br>
  <div>
    <%= f.submit 'Gravar', class: "btn btn-success" %>
  </div>
<% end %>

app/views/recipes/drafts.html.erb
<h1>Rascunhos</h1>

<div>
    <table class="table table-striped" style="text-align:center">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Tipo</th>
                <th scope="col">Culinária</th>
                <th colspan="2">Ações</th>
            </tr>
        </thead>
        <tbody>
            <% @recipes.each do |recipe| %>
                <tr>
                    <td><%= link_to recipe.name, recipe_path(recipe.id) %></td>
                    <td><%= recipe.recipe_type.name %></td>
                    <td><%= recipe.cuisine %></td>
                    <td><%= link_to 'Editar', edit_recipe_path(recipe.id), class: "btn btn-warning" %></td>
                    <td><%= button_to 'Publicar', publish_recipe_path(recipe.id), { method: 'patch', class: 'btn btn-success' } %></td>
                </tr>
            <% end %>
        </tbody>
    
</div>

app/views/recipes/edit.html.erb
<h2><strong>Edição de Receita</strong></h2>
<div>
  <%= render partial: 'form', locals: { recipe: @recipe } %>
</div>

app/views/recipes/index.html.erb
<h1>Receitas Cadastradas</h1>

<div>
    <table class="table table-striped" style="text-align:center">
        <thead>
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Tipo</th>
                <th scope="col">Culinária</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            <% @recipes.each do |recipe| %>
                <tr>
                    <td><%= link_to recipe.name, recipe_path(recipe.id) %></td>
                    <td><%= recipe.recipe_type.name %></td>
                    <td><%= recipe.cuisine %></td>
                    <td><%= link_to 'Editar', edit_recipe_path(recipe.id), class: "btn btn-warning" %></td>
                </tr>
            <% end %>
        </tbody>
    
</div>

app/views/recipes/new.html.erb
<h2><strong>Cadastro de Receita</strong></h2>
<div>
  <%= render partial: 'form', locals: { recipe: @recipe } %>
</div>

app/views/recipes/show.html.erb
<h1>Informações sobre a receita de  <%= @recipe.name %></h1>

<dl>
  <dd>
    <strong>Tipo da receita: </strong><%= @recipe.recipe_type.name if @recipe.recipe_type %>
  </dd>
  <dd>
    <strong>Culinária: </strong><%= @recipe.cuisine %>
  </dd>
  <dd>
    <strong>Ingredientes: </strong><%= @recipe.ingredients %>
  </dd>
  <dd>
    <strong>Modo de preparo: </strong><%= @recipe.cook_method %>
  </dd>
  <dd>
    <strong>Tempo de preparo: </strong><%= @recipe.cook_time %>
  </dd>
  <dd>
    <strong>Status: </strong><%= @recipe.status %>
  </dd>
</dl>

<%= button_to 'Publicar', publish_recipe_path, { method: 'patch', class: 'btn btn-primary' } if !@recipe.published?%>
<%= button_to 'Rascunho', draft_recipe_path, { method: 'patch', class: 'btn btn-primary' } if !@recipe.draft?%>